# Generated by Django 4.2.7 on 2024-03-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('publishing_date', models.DateField()),
                ('duration', models.DurationField()),
                ('date_of_event', models.DateField()),
                ('image', models.ImageField(default='', upload_to='ccrcoe/events/images')),
                ('type_of_event', models.BooleanField(choices=[(True, 'Inhouse'), (False, 'Outside')])),
                ('registeration_link', models.URLField(default=None)),
                ('event_description', models.TextField(default='')),
                ('gallery', models.FileField(blank=True, null=True, upload_to='ccrcoe/events/gallery')),
                ('comment', models.CharField(default='', max_length=200)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
