# Generated by Django 5.0.2 on 2024-03-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccrcoeweb', '0002_remove_event_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.FileField(blank=True, null=True, upload_to='ccrcoe/events/gallery'),
        ),
    ]
